language: php
php:
  - '5.5'
  - '5.4'
  - '5.3'
before_install:
  - export APP_BASE_URL='http://localhost/'
  - export APP_HOSTNAME='127.0.0.1'
  - export APP_USERNAME='travis'
  - export APP_PASSWORD=''
  - export APP_DATABASE='bpmppt_test'
  - export APP_DBPREFIX='baka_'
install:
  - npm install -g grunt-cli --silent
  - npm install --silent
  - composer install --dev --no-progress
before_script:
  - mysql -e 'drop database if exists bpmppt_test;'
  - mysql -e 'create database bpmppt_test;'
  - mysql -utravis bpmppt_test < database.sql
script:
  - grunt build
deploy:
  provider: appfog
  email: ferywardiyanto@gmail.com
  password:
    secure: aMy9J5xKm7iO6E8yA1FKZM7V2InEHoGyiezCQWrAiqVvgpmwELg/pMIWKULjQxWeMXgK0uHkwlSdHG51etU6TmhY8VTjockepnx8K3O95NGvstqIVJYSfRAbOYd85fD7NR+CQi+zx+sSiJkEveOmDwr/TxNF0aNe0PMs5a0bBfs=
  app: bpmppt
  on:
    repo: feryardiant/bpmppt
    php: '5.3'
matrix:
  fast_finish: true
branches:
  only:
    - master
