language: php
php:
  - '5.5'
  - '5.4'
  - '5.3'
before_install:
  - time npm install -g grunt-cli
  - time npm install
  - if [ "$BAKA_TEST" = php ]; then composer install; fi
install:
  - grunt test
env:
  - BAKA_TEST=php
  - BAKA_TEST=css
deploy:
  provider: appfog
  email: ferywardiyanto@gmail.com
  password:
    secure: aMy9J5xKm7iO6E8yA1FKZM7V2InEHoGyiezCQWrAiqVvgpmwELg/pMIWKULjQxWeMXgK0uHkwlSdHG51etU6TmhY8VTjockepnx8K3O95NGvstqIVJYSfRAbOYd85fD7NR+CQi+zx+sSiJkEveOmDwr/TxNF0aNe0PMs5a0bBfs=
  app: bpmppt
  on:
    repo: feryardiant/bpmppt
    php: '5.3'
