language: php
php:
  - '5.5'
  - '5.4'
  - '5.3'
before_install:
  - time npm install -g grunt-cli
  - time npm install
  - time composer install
  - mysql -e 'drop database if exists bpmppt_test;'
  - mysql -e 'create database bpmppt_test;'
  - mysql -utravis bpmppt_test < tests/backup.sql
install:
  - grunt testdist
after_script:
  - mysql -e 'drop database if exists bpmppt_test;'
deploy:
  provider: appfog
  email: ferywardiyanto@gmail.com
  password:
    secure: aMy9J5xKm7iO6E8yA1FKZM7V2InEHoGyiezCQWrAiqVvgpmwELg/pMIWKULjQxWeMXgK0uHkwlSdHG51etU6TmhY8VTjockepnx8K3O95NGvstqIVJYSfRAbOYd85fD7NR+CQi+zx+sSiJkEveOmDwr/TxNF0aNe0PMs5a0bBfs=
  app: bpmppt
  on:
    repo: feryardiant/bpmppt
    php: '5.3'
