language: php
php:
  - '5.5'
  - '5.4'
  - '5.3'
before_install:
  - npm install -g grunt-cli --silent
install:
  - npm install --silent
  - bower install --silent
  - composer install --dev --no-progress
before_script:
  - export APP_BASE_URL='http://localhost/'
  - export APP_HOSTNAME='127.0.0.1'
  - export APP_USERNAME='travis'
  - export APP_PASSWORD=''
  - export APP_DATABASE='bpmppt_test'
  - export APP_DBPREFIX='baka_'
  - mysql -e 'create database if not exists bpmppt_test;'
  - mysql -utravis bpmppt_test < database.sql
script:
  - grunt build
after script:
  - mysql -e 'drop database if exists bpmppt_test;'
matrix:
  fast_finish: true
